# Generated by Django 3.2.5 on 2021-07-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
    ]
