# Generated by Django 3.2.5 on 2021-07-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_list_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='list',
            old_name='created_at',
            new_name='title',
        ),
    ]
