# Generated by Django 3.2.5 on 2021-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210711_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='number_done_tasks',
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
