# Generated by Django 3.2.5 on 2021-07-24 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline2',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
