# Generated by Django 3.2.5 on 2021-07-24 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deadline2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deadline2',
            new_name='deadline'
        ),
    ]
