# Generated by Django 3.2.5 on 2021-07-14 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210714_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 18, 32, 47, 447732, tzinfo=utc)),
        ),
    ]
